spring.application.name=Dockerdemo

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/StudentDb
spring.datasource.username=postgres
spring.datasource.password=sonal321


spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.sql.init.platform=postgres
spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:data.sql